<?xml version="1.0"?>

<robot name="led_mr" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="wheel_r" value="0.1" />
    <xacro:property name="wheel_w" value="0.05" />
    <xacro:property name="wheel_s" value="0.35" />
    <xacro:property name="body_x" value="0.3" />
    <xacro:property name="body_y" value="0.3" />
    <xacro:property name="body_z" value="0.05" />

    <material name="BLUE">
        <color rgba="0.0 0.0 1.0 1.0"/>
    </material>
    <material name="WHITE">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>

    <link name="body_footprint">
        <visual>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
        </visual>
    </link>
    
    <link name="body">
        <collision>
            <geometry>
                <box size="${body_x} ${body_y} ${body_z}"/>
            </geometry>
        </collision>
        <visual>
            <geometry>
                <box size="${body_x} ${body_y} ${body_z}"/>
            </geometry>
            <material name="WHITE"/>
        </visual>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="4.77"/>
            <inertia ixx="0.03975" ixy="0.0" ixz="0.0" iyy="0.07155" iyz="0.0" izz="0.03975"/>
        </inertial>
    </link>

    <link name="l_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_r}" length="${wheel_w}"/>
            </geometry>
            <material name="BLUE"/>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_r}" length="${wheel_w}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <mass value="1.665"/>
            <inertia ixx="0.008325" ixy="0.0" ixz="0.0" iyy="0.00555" iyz="0.0" izz="0.00555"/>
        </inertial>
    </link>

    <link name="r_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_r}" length="${wheel_w}"/>
            </geometry>
            <material name="BLUE"/>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_r}" length="${wheel_w}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
        </collision>
        <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
            <mass value="1.665"/>
            <inertia ixx="0.008325" ixy="0.0" ixz="0.0" iyy="0.0555" iyz="0.0" izz="0.0555"/>
        </inertial>
    </link>

    <link name="l_indic">
        <visual>
            <origin xyz="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.002 0.005 ${wheel_r}"/>
            </geometry>
        </visual>
    </link>

    <link name="r_indic">
        <visual>
            <origin xyz="0.0 0.0 0.0"/>
            <geometry>
                <box size="0.002 0.005 ${wheel_r}"/>
            </geometry>
        </visual>
    </link>

    <joint name="body_to_footprint" type="fixed">
        <origin xyz="0.0 0.0 ${wheel_r}"/>
        <parent link="body_footprint"/>
        <child link="body"/>
    </joint>

    <joint name="l_wheel_indic" type="fixed">
        <origin xyz="-${wheel_w/2} 0.0 ${wheel_r/2}"/>
        <parent link="l_wheel"/>
        <child link="l_indic"/>
    </joint>
    
    <joint name="r_wheel_indic" type="fixed">
        <origin xyz="-${wheel_w/2} 0.0 ${wheel_r/2}"/>
        <parent link="r_wheel"/>
        <child link="r_indic"/>
    </joint>

    <joint name="body_to_left_wheel" type="continuous">
        <origin xyz="0.0 -${wheel_s/2} 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="body"/>
        <child link="l_wheel"/>
        <axis xyz="0.0 1.0 0.0"/>
        <!-- <limit lower="0.0" upper="0.0" effort="0.0" velocity="10.0"/> -->
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>

    <joint name="body_to_right_wheel" type="continuous">
        <origin xyz="0.0 ${wheel_s/2} 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="body"/>
        <child link="r_wheel"/>
        <axis xyz="0.0 1.0 0.0"/>
        <!-- <limit lower="0.0" upper="0.0" effort="0.0" velocity="10.0"/> -->
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>

    <transmission name="l_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="body_to_left_wheel">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="l_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="r_tran">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="body_to_right_wheel">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="r_motor">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <!-- ros_control plugin -->
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/led_mr</robotNamespace>
        <!-- <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType> -->
        </plugin>
    </gazebo>

    <!-- Link1 -->
    <gazebo reference="body">
        <material>Gazebo/Orange</material>
    </gazebo>
    
    <!-- Link2 -->
    <gazebo reference="l_wheel">
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
        <kp>1000000.0</kp>
        <kd>100.0</kd>
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- Link3 -->
    <gazebo reference="r_wheel">
        <mu1>0.2</mu1>
        <mu2>0.2</mu2>
        <kp>1000000.0</kp>
        <kd>100.0</kd>
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="l_indic">
        <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="r_indic">
        <material>Gazebo/Red</material>
    </gazebo>
</robot>